{
 "title": "Kong Gateway (All Clusters)",
 "tags": [
  "kong",
  "api-gateway"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kong_nginx_connections_total,instance)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(kong_http_requests_total,service)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values(kong_http_requests_total,route)"
    }
   },
   {
    "name": "upstream",
    "query": {
     "query": "label_values(kong_upstream_target_health, upstream)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Caching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kong shared memory usage by Node ($instance)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kong_memory_lua_shared_dict_bytes{instance=~\"$instance\",shared_dict!~\"kong_process_events\"}/kong_memory_lua_shared_dict_total_bytes{instance=~\"$instance\",shared_dict!~\"kong_process_events\"})*100",
     "legendFormat": "{{shared_dict}} ({{kong_subsystem}})"
    }
   ]
  },
  {
   "title": "Kong worker Lua VM usage by Node ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kong_memory_workers_lua_vms_bytes{instance=~\"$instance\"}",
     "legendFormat": "PID:{{pid}} ({{kong_subsystem}})"
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Nginx connection state",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kong_nginx_connections_total{state=~\"active|reading|writing|waiting\", instance=~\"$instance\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kong_nginx_connections_total{state=\"total\", instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Handled Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kong_nginx_connections_total{state=\"handled\", instance=~\"$instance\"})",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Accepted Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kong_nginx_connections_total{state=\"accepted\", instance=~\"$instance\"})",
     "legendFormat": "Accepted"
    }
   ]
  },
  { "title": "Request Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Total requests per second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Requests/second"
    }
   ]
  },
  {
   "title": "RPS per route/service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "RPS per route/service by status code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (service,code)",
     "legendFormat": "service:{{service}}-{{code}}"
    },
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (route,code)",
     "legendFormat": "route:{{route}}-{{code}}"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Kong Proxy Latency across all services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Kong Proxy Latency per Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
     "legendFormat": "p90-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
     "legendFormat": "p95-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
     "legendFormat": "p99-{{service}}"
    }
   ]
  },
  {
   "title": "Kong Proxy Latency per Route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "p90-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "p95-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "p99-{{route}}"
    }
   ]
  },
  {
   "title": "Request Time across all services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Request Time per service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
     "legendFormat": "p90-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
     "legendFormat": "p95-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
     "legendFormat": "p99-{{service}}"
    }
   ]
  },
  {
   "title": "Request Time per Route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "p90-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "p95-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "p99-{{route}}"
    }
   ]
  },
  {
   "title": "Upstream time across all services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Upstream Time per service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
     "legendFormat": "p90-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
     "legendFormat": "p95-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
     "legendFormat": "p99-{{service}}"
    }
   ]
  },
  {
   "title": "Upstream Time per Route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "p90-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "p95-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "p99-{{route}}"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth_bytes{instance=~\"$instance\"}[1m])) by (direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Egress per service/route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth_bytes{direction=\"egress\", service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(irate(kong_bandwidth_bytes{direction=\"egress\", service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "Ingress per service/route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth_bytes{direction=\"ingress\", service=~\"$service\",instance=~\"$instance\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Upstream Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Upstream Target Health Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(label_replace(label_replace(label_replace(kong_upstream_target_health{upstream=~\"$upstream\"}, \"state_value\", \"1\", \"state\", \"healthy\"), \"state_value\", \"0\", \"state\", \"healthchecks_off\"), \"state_value\", \"-1\", \"state\", \"(dns_error|unhealthy)\")) by (upstream, target, address, state, state_value) > 0"
    }
   ]
  },
  { "title": "Stream Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Stream Sessions per Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kong_stream_session_total{instance=~\"$instance\"}[1m])) by (service,code)",
     "legendFormat": "{{service}}-{{code}}"
    }
   ]
  }
 ]
}