name: Release

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create CalVer Release
        uses: Nvision-x/gh-actions-calver@2025.09.23-2
        with:
          # Create release automatically
          create_release: true
          # Use CalVer format: YYYY.MM.DD
          calver_format: "YYYY.MM.DD"
          # Tag prefix (optional)
          tag_prefix: "v"
          # Generate release notes from commits
          generate_release_notes: true
          # Include all files in the release
          release_files: |
            dashboards/*.json
            alerts/*.json
            datasources/*.json
            folders/*.json
            *.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
